MODEL:
  PRECISION: ""
  CHECKPOINT_PATH: ""

DATA:
  DATA_ROOT: ""

SOLVER:
  OPTIMIZER_NAME: "AdamW"
  MAX_EPOCHS: 10
  MAX_STEPS: 0
  BASE_LR: 0.0001
  BIAS_LR_FACTOR: 2
  WEIGHT_DECAY: 0.01
  WEIGHT_DECAY_BIAS: 0.0
  SCHED: "WarmupLinearLR"
  WARMUP_METHOD: "linear"
  WARMUP_STEP_RATIO: 0.05
  WARMUP_FACTOR: 0.01
  GAMMA: 0.9
  AGB: 1
  TRAIN_BSZ: 16
  VALID_BSZ: 32

WANDB:
  KEY: 'db6dc4900419e1e9ec25f50a80a3b5712b95b88c'
