from task.task import Task
from task.trainer import seed_everything, Trainer
from admet_predictor.Transformer.criterions.cls_and_reg import FinetuneCrossEntropyLoss, FinetuneMSELoss
from admet_predictor.Transformer.models.transformer_m import TransformerMModel
from admet_predictor.Transformer.models.bemt2 import BEMT
from admet_predictor.Transformer.criterions.molecule_predict import MultiTaskBCELoss, FinetuneCrossEntropyLoss, FinetuneMSELoss, FinetuneSmoothMAELoss
# from admet_predictor.Transformer.models.cress_admet import MultiTaskCress
# from Transformer.criterions.graph_prediction import GraphPredictionLoss
from admet_predictor.datasets import GraphDatasets
from admet_predictor.Transformer.criterions.bemt_pretrain import BEMTPretrainLoss
from admet_predictor.Transformer.criterions.bemt_admet import GraphPredictionLoss