MODEL:
  TOKENIZER_PATH: './tokenizer/chembl_pubchem10M/tokenizer.json'
  CHECKPOINT_PATH: './save/FragGPT_pocket_pretrain_drugs2'
  USE_MODEL_CKPT: True
  MODEL_NAME: 'FragGPT_pocket_pretrain_drugs2_5.pt'
  USE_EMA: False
  POCKET_ENCODER:
    encoder_layers: 6
    encoder_embed_dim: 768
    encoder_ffn_embed_dim: 768
    encoder_attention_heads: 32
    dropout: 0.2
    emb_dropout: 0.0
    attention_dropout: 0.1
    activation_dropout: 0.0
    activation_fn: gelu
    post_ln: False

  GPT_MODEL:
    n_layer: 12
    n_head: 8
    n_embd: 768

  ADMET_ENCODER:
    use_admet: False
    n_embd: 768
    n_head: 8
    n_layer: 3 # 3

  ADAPTER:
    use_adapter: False
    adapter_name: drugs
    REDUCTION_FACTOR: 16
    ACTIVATION: 'gelu'

  PEFT:
    LoRA: True
    OPEN: False

SOLVER:
  TRAIN_BSZ: 16 # 104
  VALID_BSZ: 16 # 104
  MAX_EPOCHS: 50
  WARMUP_STEP_RATIO: 0.05
  WEIGHT_DECAY: 0.0
  OPTIMIZER_NAME: "AdamW"
  BASE_LR: 1.0e-4
  NUM_WORKERS: 8
  GRADIENT_ACC: 1
  LR_SCHEDULER: "linear"
  CLIP_GRAD: False
  SAVE_STEP: 1
  PEPOCH: 0.9

DATA:
  DATA_ROOT: "/mnt/e/tangui/SMILES_NEW/data/menin/NOVA008.csv"
  POCKET: "/mnt/e/tangui/SMILES_NEW/data/menin"
  MAX_SMILES_LEN: 512
  VOCAB_SIZE: 1000
  MIN_FREQUENCY: 2
  MAX_RES_LEN: 200
